global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['node-exporter:9100'] ## IP Address of the localhost